target=./conference_pricing.out
input=./conference_pricing_input.bin
output_dir=./out
listen_addr=127.0.0.1:50051
use_stdin=true
debug=false
bounds_check=false
solve_ub=false
run_timeout_ms=5000
solve_timeout_ms=5000
max_runs=1000
args=./conference_pricing.out {input}
